version: "3.8"

services:
  food-service:
    build:
      context: ./food-service
      dockerfile: Dockerfile.dev
    container_name: food-service
    env_file:
      - .env
      - ./food-service/.env
    networks:
      - fitness-network
    volumes:
      - ./food-service:/app
      - maven-repo:/root/.m2
    restart: unless-stopped

  statistic-service:
    build:
      context: ./statistic-service
      dockerfile: Dockerfile.dev
    container_name: statistic-service
    env_file:
      - .env
      - ./statistic-service/.env
    networks:
      - fitness-network
    volumes:
      - ./statistic-service:/app
      - maven-repo:/root/.m2
    restart: unless-stopped

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile.dev
    container_name: media-service
    env_file:
      - .env
      - ./media-service/.env
    networks:
      - fitness-network
    volumes:
      - ./media-service:/app
      - maven-repo:/root/.m2
    restart: unless-stopped

  exercise-service:
    build:
      context: ./exercise-service
      dockerfile: Dockerfile.dev
    container_name: exercise-service
    env_file:
      - .env
      - ./exercise-service/.env
    networks:
      - fitness-network
    volumes:
      - ./exercise-service:/app
      - maven-repo:/root/.m2
    restart: unless-stopped

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile.dev
    container_name: gateway-service
    ports:
      - "${GATEWAY_SERVICE_PORT:-8088}:8088"
    env_file:
      - .env
      - ./gateway-service/.env
    environment:
      - FOOD_SERVICE_HOST=http://food-service:8080
      - STATISTIC_SERVICE_HOST=http://statistic-service:8081
      - EXERCISE_SERVICE_HOST=http://exercise-service:8082
      - MEDIA_SERVICE_HOST=http://media-service:8083
      - KEYCLOAK_AUTH_SERVER_HOST=http://keycloak-auth-server:8888
    networks:
      - fitness-network
    volumes:
      - ./gateway-service:/app
      - maven-repo:/root/.m2
    restart: unless-stopped

  keycloak-auth-server:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak-auth-server
    ports:
      - "${KEYCLOAK_AUTH_SERVER_PORT:-8888}:8888"
    env_file:
      - .env
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      # - KC_HOSTNAME=10.0.2.2
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=${KEYCLOAK_AUTH_SERVER_PORT:-8888}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_LOG_LEVEL=info
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
    networks:
      - fitness-network
    command: start-dev --http-port=${KEYCLOAK_AUTH_SERVER_PORT:-8888}
    restart: unless-stopped

networks:
  fitness-network:
    driver: bridge

volumes:
  maven-repo:
