FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    postgresql-client \
    maven \
    && apt-get clean

EXPOSE 8088

CMD ["sh", "-c", "cd /app && mvn spring-boot:run"] 